---
- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  scm: git

- name: nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  # TODO: update hash and find a working image to support topic argument change
  version: 8044c33ffb92b3ee73cba677a090330ff638b70c
  scm: git
